Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "base.littleobi.com"
  c.vm.hostname = "base.littleobi.com"
  c.vm.network(:private_network, {:ip=>"172.253.253.0"})
  c.vm.network(:forwarded_port, {:guest=>80, :host=>8480})
  c.vm.network(:forwarded_port, {:guest=>443, :host=>4343})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-lyn-infra-base-baselittleobicom-54e67aec-0300-4562-90f0-5693525b9e1e"
    p.customize ["modifyvm", :id, "--audio", "none"]
    p.customize ["modifyvm", :id, "--memory", "2048"]
    p.customize ["modifyvm", :id, "--cpus", "2"]
  end
end
