name 'linux_patching'
maintainer 'Dan Gordon'
maintainer_email 'chef@dangordon.xyz'
license 'Apache-2.0'
description 'A Chef cookbook to patch Linux nodes.'
version '0.1.2'
chef_version '>= 14.0'
source_url 'https://gitlab.com/dg42/chef_linux_patching'
issues_url 'https://gitlab.com/dg42/chef_linux_patching/issues'

supports 'amazon'
supports 'arch'
supports 'centos'
supports 'debian'
supports 'redhat'
supports 'ubuntu'

depends 'cron', '~> 6.2.1'
