Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-8"
  c.vm.hostname = "base.littleobi.com"
  c.vm.network(:private_network, {:ip=>"172.253.253.0"})
  c.vm.network(:forwarded_port, {:guest=>80, :host=>8480})
  c.vm.network(:forwarded_port, {:guest=>443, :host=>4343})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "C:/Users/tarak/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-lyn-infra-base-centos-8-77c2dae8-45cb-4354-8e1a-7ae4860ca7a6"
    p.customize ["modifyvm", :id, "--audio", "none"]
    p.customize ["modifyvm", :id, "--memory", "2048"]
    p.customize ["modifyvm", :id, "--cpus", "2"]
  end
end
